repos:
-   repo: github.com/PyCQA/pydocstyle
    rev: 1.6.0
    hooks:
    -   id: docformatter
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--line-length=79]
